@_03_Redis.DistributedCache_HostAddress = http://localhost:5184

GET {{_03_Redis.DistributedCache_HostAddress}}/products/
Accept: application/json

###
GET {{_03_Redis.DistributedCache_HostAddress}}/products/4
Accept: application/json

###

PATCH {{_03_Redis.DistributedCache_HostAddress}}/products/4
Accept: application/json

###
