@_02_CacheAside.Api_HostAddress = http://localhost:5259

GET {{_02_CacheAside.Api_HostAddress}}/orders/
Accept: application/json

###

GET {{_02_CacheAside.Api_HostAddress}}/orders/5
Accept: application/json

###

PATCH {{_02_CacheAside.Api_HostAddress}}/orders/5
Accept: application/json

###